### ISSUE TITLE
DNS FQDN pointers need to be dot terminated

### ISSUE THREAD

**Issue by notCalle** [saab-simc-admin/palletjack#49]

**Comment by creideiki** [comment]
`palletjack2knot` (and perhaps other tools?) assume that data stored in the warehouse is non-dot-terminated FQDN:s, and add dots unconditionally. As per #48, we want to be able to have either short names or FQDN:s. Update the tools.

**Comment by creideiki** [comment]
Code written in [creideiki:dot-dns-names](https://github.com/creideiki/palletjack/tree/dot-dns-names), but not submitted since I don't have my signing key on me.

Only MX exchange, NS NSDNAME and SOA MNAME actually come from the warehouse and are affected. We add a bunch of other trailing dots in `palletjack2knot`, but those are on names we generate internally and know to be absolute.

**Comment by notCalle** [comment]
This change broke `palletjack2unbound` IP address matching for NS records, because the NS records don't exactly match the FQDN of an ipv4_interface anymore.

``` ruby
    domain['net.dns.ns'].each do |ns|
      jack['ipv4_interface', with_all:{'net.dns.fqdn' => ns}].each do |ipv4|
        stub_addrs << ipv4['net.ipv4.address']
      end
    end
```

Probably should be filed as a bug against `palletjack2unbound` instead... with reference to this or the pull request or something.

**Comment by notCalle** [comment]
The bug is in palletjack2unbound, not with this code.
